server {
    listen       $PORT;
    server_name  localhost;

    # Enforce strict MIME type definitions
    include /etc/nginx/mime.types;
    types {
        application/javascript js mjs;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # SPA routing: fallback to index.html
        try_files $uri $uri/ /index.html;
    }

    # Cache static assets
    location ~* \.(?:ico|css|js|mjs|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        root /usr/share/nginx/html;
        include /etc/nginx/mime.types;
        try_files $uri =404;
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
